### ISSUE TITLE
Export video of score possible?

### ISSUE THREAD

**Issue by ultraGentle** [LibreScore/webmscore#8]
Can WebMScore export a video of the score, like MuseScore?  

I did not see video as an export option in the source code, but I wasn't sure if I was missing something.

**Comment by ultraGentle** [comment]
I apologize, I was thinking of Sibelius -- Musescore does not have video export, so nevermind.

**Comment by CarlGao4** [comment]
Hey, now you can try [mscz2video](https://github.com/CarlGao4/mscz-to-video)
